### ISSUE TITLE
Error: Command failed: npx prisma generate

### ISSUE THREAD

**Issue by pixelprogrammer** [danieluhm2004/serverless-webpack-prisma#15]
## Issue

This error occurs when running `serverless deploy`. Here is the full error message:

```shell
agent_1  | Error: Command failed: npx prisma generate
agent_1  | Error: Could not resolve @prisma/client despite the installation that we just tried.
agent_1  | Please try to install it by hand with npm install @prisma/client and rerun prisma generate ?.
agent_1  | 
agent_1  |     at checkExecSyncError (child_process.js:790:11)
agent_1  |     at Object.execSync (child_process.js:863:15)
agent_1  |     at ServerlessWebpackPrisma.generatePrismaSchema (/codebuild/output/srcDownload/src/node_modules/serverless-webpack-prisma/src/index.js:94:18)
agent_1  |     at ServerlessWebpackPrisma.onBeforeWebpackPackage (/codebuild/output/srcDownload/src/node_modules/serverless-webpack-prisma/src/index.js:48:12)
agent_1  |     at PluginManager.runHooks (/codebuild/output/srcDownload/src/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
agent_1  |     at PluginManager.invoke (/codebuild/output/srcDownload/src/node_modules/serverless/lib/classes/plugin-manager.js:565:20)
agent_1  |     at async PluginManager.spawn (/codebuild/output/srcDownload/src/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
```

## Source Files and Environment

I am testing this build process locally (happens on production too) with aws `codebuild_script` and their docker image (built from source) using `standard:5.0`.

**buildspec.yml**
```yaml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i
  build:
    commands:
      # This is for something else, not relevant
      - npm run build
  post_build:
    commands:
      # This command succeeds
      - npx prisma generate
      # This runs serverless deploy and fails with the error posted earlier
      - npm run lambda:deploy

artifacts:
  files:
    - .platform/**/*
    - dist/**/*
    - package.json
    - node_modules/**/*
    - '!node_modules/.prisma/client/query-engine-*'
    - node_modules/.prisma/client/query-engine-rhel-*

```
**serverless.yml**
```yaml
service: our-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_REGION}
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${env:NODE_ENV}
    DATABASE_URL: ${env:DATABASE_URL}

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline

functions:
  our-function:
    handler: ./src/handlers/our-function.handler
    events:
      - schedule: rate(1 minute)

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

```
**package.json**
```json
{
    "dependencies": {
        "@aws-sdk/client-ec2": "^3.34.0",
        "@aws-sdk/client-s3": "^3.34.0",
        "@nexrender/action-encode": "^1.28.2",
        "@nexrender/action-upload": "^1.21.3",
        "@nexrender/core": "^1.31.0",
        "@nexrender/provider-s3": "^1.32.0",
        "@prisma/client": "3.15.2",
        "@sentry/node": "^6.12.0",
        "@sentry/serverless": "^6.15.0",
        "@sentry/tracing": "^6.13.2",
        "express": "^4.17.1",
        "express-validator": "^6.12.2",
        "helmet": "^4.6.0",
        "jsonwebtoken": "^8.5.1",
        "multer": "^1.4.3",
        "prisma": "3.15.2",
        "serverless": "^3.21.0",
        "serverless-offline": "^8.2.0",
        "serverless-webpack": "^5.5.4",
        "serverless-webpack-prisma": "^1.1.0",
        "tar": ">=6.1.9",
        "uuid": "^8.3.2",
        "webpack": "^5.56.0",
        "webpack-node-externals": "^3.0.0"
      },
      "devDependencies": {
        "@types/cookie-parser": "^1.4.2",
        "@types/jest": "^27.0.2",
        "@types/jsonwebtoken": "^8.5.5",
        "@types/uuid": "^8.3.1",
        "@types/aws-lambda": "^8.10.83",
        "@types/cors": "^2.8.12",
        "@types/express": "^4.17.13",
        "@types/multer": "^1.4.7",
        "@types/node": "^16.10.2",
        "@types/react": "^17.0.27",
        "@typescript-eslint/eslint-plugin": "^4.32.0",
        "@typescript-eslint/parser": "^4.32.0",
        "eslint": "^7.32.0",
        "ts-loader": "^9.2.6",
        "nodemon": "^2.0.13",
        "prettier": "^2.4.1",
        "ts-jest": "^27.0.5",
        "typescript": "^4.4.3",
        "ts-node": "^10.2.1"
      }
}
```

### Prisma Versions
Tested with `prisma` and `@prisma/client` versions `3.3.0` and `3.15.2`

## When the error occurred

This setup used to work at one point. Its possible, that something may have updated on our end which could've caused it so I am not ruling that out but if there is something here that is obvious it would be good to know.
